#!/usr/bin/env bun
// ============================================================================
// Maker: open + fund a bounty (ERC-8183 Job) on BountyEscrow.
//
//   1. Hash the PRIVATE bundle (tests + rubric) -> testsHash commitment.
//   2. approve() the reward token to the escrow.
//   3. createBounty(budget, deadline, testsHash, specCid).
//
// The PRIVATE files are committed only as a hash; the public spec/tests are
// referenced by specCid. Tests/rubric are generated by Claude (the maker agent).
//
// Usage:
//   SEP_PRIVATE_KEY=... bun maker/create-bounty.ts [rewardUSDC] [hoursToDeadline] [bountyDir]
// ============================================================================

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { execSync } from "node:child_process";

const RPC = process.env.RPC ?? "https://ethereum-sepolia-rpc.publicnode.com";
const PK = process.env.SEP_PRIVATE_KEY;
const ESCROW = process.env.ESCROW ?? "0xC0543ac495B24948Ad84cD15d8488d7Af2F9ca90";
const USDC = process.env.USDC ?? "0x3211C5E4B4d57B673d67a976699121667f419e17";
if (!PK) throw new Error("SEP_PRIVATE_KEY not set");

const reward = Number(process.argv[2] ?? 50); // human USDC (6dp token)
const hours = Number(process.argv[3] ?? 1);
const bountyDir = process.argv[4] ?? "maker/bounties/uniswap-lp-trading-bot";

// 1. Commitment to the PRIVATE bundle (fixed order, never published).
const privateFiles = ["private/rubric.md", "private/scoring.py", "private/prices_private.json"];
const bundle = privateFiles.map((f) => readFileSync(`${bountyDir}/${f}`, "utf8")).join("\n--FILE--\n");
const testsHash = "0x" + createHash("sha256").update(bundle).digest("hex");

const budget = BigInt(Math.round(reward * 1e6)); // 6-decimal token base units
const deadline = Math.floor(Date.now() / 1000) + hours * 3600;
const specCid = process.env.SPEC_CID ?? `honeycomb://${bountyDir.split("/").pop()}/spec.md`; // TODO: real IPFS CID

const sh = (cmd: string) => execSync(cmd, { encoding: "utf8" }).trim();
const cast = (args: string) => sh(`cast ${args} --rpc-url ${RPC}`);
const send = (args: string) => sh(`cast send ${args} --private-key ${PK} --rpc-url ${RPC} --json`);

console.error(`[maker] reward=${reward} mUSDC  budget=${budget}  deadline=+${hours}h  testsHash=${testsHash}`);
console.error(`[maker] specCid=${specCid}`);

// 2. approve the escrow to pull the reward.
console.error(`[maker] approving ${budget} to escrow...`);
send(`${USDC} "approve(address,uint256)" ${ESCROW} ${budget}`);

// 3. createBounty — read the real jobId from the JobCreated event (topics[1]),
//    not nextJobId (a concurrent creation could shift it).
console.error(`[maker] creating bounty...`);
const receipt = JSON.parse(
	send(`${ESCROW} "createBounty(uint256,uint64,bytes32,string)" ${budget} ${deadline} ${testsHash} "${specCid}"`),
);
const log = (receipt.logs ?? []).find((l: any) => l.address?.toLowerCase() === ESCROW.toLowerCase());
if (!log) throw new Error("JobCreated event not found in receipt");
const jobId = BigInt(log.topics[1]).toString(); // keep as string — ids can exceed 2^53

console.error(`[maker] done. jobId=${jobId}`);
console.log(JSON.stringify({ jobId, budget: budget.toString(), deadline, testsHash, specCid }, null, 2));
