#!/usr/bin/env bun
// ============================================================================
// Maker: open + fund a bounty (ERC-8183 Job) on BountyEscrow.
//
//   1. Hash the PRIVATE bundle (every file under <bountyDir>/private/, sorted)
//      -> testsHash commitment. Works for any bounty dir, not a fixed file list.
//   2. approve() the reward token to the escrow.
//   3. createBounty(budget, deadline, testsHash, specCid, attesterKey, makerPubKey).
//
// The DEPLOYED escrow is the 6-arg version (BountyEscrow.sol:153): the score
// signature is bound on-chain to `attesterKey` (the execution enclave's score-
// signer the contract ecrecovers grades against, BountyEscrow.sol:248) and the
// maker's X25519 `makerPubKey` (the grader seals the winner's code to it). Both
// are required — the contract reverts on a zero attester or a zero maker key
// (BountyEscrow.sol:162-163).
//
// The PRIVATE files are committed only as a hash; the public spec/tests are
// referenced by specCid. Tests/rubric are generated by Claude (the maker agent).
//
// Usage:
//   SEP_PRIVATE_KEY=... bun maker/create-bounty.ts [rewardUSDC] [hoursToDeadline] [bountyDir]
// ============================================================================

import { createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
// grading-cre is outside the pnpm workspace, so reach the shared constant by
// relative path; bun resolves the .ts directly. Single source: packages/chain.
import { SEPOLIA_RPC } from "../../../packages/chain/sepolia.ts";

const RPC = SEPOLIA_RPC;
const PK = process.env.SEP_PRIVATE_KEY;
const ESCROW = process.env.ESCROW ?? "0xC0543ac495B24948Ad84cD15d8488d7Af2F9ca90";
const USDC = process.env.USDC ?? "0x3211C5E4B4d57B673d67a976699121667f419e17";
if (!PK) throw new Error("SEP_PRIVATE_KEY not set");

const reward = Number(process.argv[2] ?? 50); // human USDC (6dp token)
const hours = Number(process.argv[3] ?? 1);
const bountyDir = process.argv[4] ?? "maker/bounties/uniswap-lp-trading-bot";
// Grader enclave's score signer (ecrecover target, BountyEscrow.sol:248) + maker's
// X25519 delivery pubkey. Both are sent on-chain to the 6-arg createBounty; the
// contract reverts on a zero attester or maker key. Live KMS signer (apps/grading-
// cre/grader/HANDOFF.md:88). Override MAKER_PUBKEY with the real maker key.
const ATTESTER = process.env.ATTESTER ?? "0x5B57aF5eBAd44bEEfdfCcd71F33359d74Ec0e86F";
const MAKER_PUBKEY = process.env.MAKER_PUBKEY ?? `0x${"11".repeat(32)}`;

// 1. Commitment to the PRIVATE bundle (never published). Hash whatever lives
//    under the passed dir's private/ — sorted so the order is deterministic
//    (readdir order is not; sort is load-bearing for a stable digest).
//
//    testsHash is an OPAQUE publish-time commitment that pins the private inputs
//    at bounty-creation time. It is NOT recomputed or checked by the grader: the
//    grader hashes only the single PRIVATE_SERIES file (grade.ts:69), a different
//    preimage entirely. On-chain it is write-only — stored + emitted, never read
//    back (BountyEscrow.sol:159,163). Its job is to let anyone who later obtains
//    the private files prove they match what the maker pinned, nothing more.
//
//    Read each file as a raw Buffer (no encoding) so the digest is byte-exact and
//    survives non-UTF8 / binary private files. Drop dotfiles (.DS_Store etc.) so
//    OS cruft can't perturb the commitment, and fail loud on an empty dir rather
//    than committing sha256("") — an all-files-missing bug must not pass silently.
const privateFiles = readdirSync(`${bountyDir}/private`)
	.filter((f) => !f.startsWith("."))
	.sort();
if (privateFiles.length === 0) throw new Error(`no private files under ${bountyDir}/private`);
const bundle = Buffer.concat(
	privateFiles.flatMap((f, i) => {
		const data = readFileSync(`${bountyDir}/private/${f}`); // Buffer, no encoding
		return i === 0 ? [data] : [Buffer.from("\n--FILE--\n"), data];
	}),
);
const testsHash = "0x" + createHash("sha256").update(bundle).digest("hex");

const budget = BigInt(Math.round(reward * 1e6)); // 6-decimal token base units
// Deadline = now + hours*3600, unless DEADLINE_SECS overrides (for a quick demo:
// a ~180s deadline lets resolve fire in the same sitting; resolve gates on
// block.timestamp > expiredAt, BountyEscrow.sol:234).
const deadline =
	Math.floor(Date.now() / 1000) + (process.env.DEADLINE_SECS ? Number(process.env.DEADLINE_SECS) : hours * 3600);
const specCid = process.env.SPEC_CID ?? `honeycomb://${bountyDir.split("/").pop()}/spec.md`; // TODO: real IPFS CID

// Shell out to `cast` via execFileSync with an ARGS ARRAY — no shell parsing, so
// nothing here is an injection surface and the secret RPC never lands on argv:
// cast reads it from ETH_RPC_URL in the child env. The private key still goes via
// --private-key (cast has no env var for a raw key), so it is on the child's argv
// (visible to local `ps`) — an inherent cast limitation, not a shell leak. The
// catch scrubs the key and any ?secret= so a cast failure can never echo either.
const childEnv = { ...process.env, ETH_RPC_URL: RPC };
const scrub = (s: string) =>
	(PK ? s.split(PK).join("<redacted-key>") : s).replace(/secret=[^&\s"']+/gi, "secret=<redacted>");
function cast(args: string[]): string {
	try {
		return execFileSync("cast", args, { encoding: "utf8", env: childEnv }).trim();
	} catch (e: any) {
		// execFileSync errors carry the full argv (incl. --private-key) on .message
		// and may carry it on .stderr. Re-throw a scrubbed message so neither the
		// key nor the secret RPC can reach a log.
		const detail = scrub((e?.stderr?.toString() || e?.message || String(e)).trim());
		throw new Error(`cast ${scrub(args[0] ?? "")} failed: ${detail}`);
	}
}
// `cast send` with the signer. PK is non-null here (checked at top).
const send = (args: string[]) => cast(["send", ...args, "--private-key", PK as string, "--json"]);

console.error(`[maker] reward=${reward} mUSDC  budget=${budget}  deadline=+${hours}h  testsHash=${testsHash}`);
console.error(`[maker] specCid=${specCid}  attesterKey=${ATTESTER}  makerPubKey=${MAKER_PUBKEY}`);

// 2. approve the escrow to pull the reward. `cast send` exits 0 even when the tx
//    mined-but-reverted, so inspect the receipt status: a reverted approve would
//    otherwise surface later as an opaque createBounty revert on transferFrom.
console.error(`[maker] approving ${budget} to escrow...`);
const approveReceipt = JSON.parse(send([USDC, "approve(address,uint256)", ESCROW, budget.toString()]));
if (approveReceipt.status !== "0x1") {
	throw new Error(`approve reverted (status=${approveReceipt.status}, tx=${approveReceipt.transactionHash})`);
}

// 3. createBounty — read the real jobId from the JobCreated event (topics[1]),
//    not nextJobId (a concurrent creation could shift it).
console.error(`[maker] creating bounty...`);
const receipt = JSON.parse(
	// 6-arg: matches the DEPLOYED escrow (BountyEscrow.sol:153). attesterKey binds
	// the grade signature (ecrecover) and makerPubKey is the X25519 delivery key; the
	// contract reverts on a zero attester or zero maker key. Sent via the execFileSync
	// args-array form (send) — no shell, so operands are not an injection surface.
	send([
		ESCROW,
		"createBounty(uint256,uint64,bytes32,string,address,bytes32)",
		budget.toString(),
		deadline.toString(),
		testsHash,
		specCid,
		ATTESTER,
		MAKER_PUBKEY,
	]),
);
const log = (receipt.logs ?? []).find((l: any) => l.address?.toLowerCase() === ESCROW.toLowerCase());
if (!log) throw new Error("JobCreated event not found in receipt");
const jobId = BigInt(log.topics[1]).toString(); // keep as string — ids can exceed 2^53

console.error(`[maker] done. jobId=${jobId}`);
console.log(JSON.stringify({ jobId, budget: budget.toString(), deadline, testsHash, specCid }, null, 2));
